name: lessay_learn
description: "lessay learn"

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  go_router:
  dio: 
  json_annotation: 
  cupertino_icons: 
  hive: 
  hive_flutter: 
  get_it: 
  intl: ^0.19.0
  mocktail: ^1.0.4
  equatable: ^2.0.5
  uuid: ^4.5.0
  fl_chart: ^0.69.0
  word_cloud: ^1.0.3
  flutter_tts: ^3.8.5
  just_the_tooltip: ^0.0.12
  file_picker: ^8.1.2
  csv: ^6.0.0
  firebase_core: 
  firebase_auth: 
  google_sign_in: 
  translator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  path_provider_platform_interface:
  plugin_platform_interface:

flutter:
  uses-material-design: true
  assets:
  - assets/blank.png
  - assets/avatar-1.png
  - assets/avatar-2.png
  - assets/avatar-3.png
  - assets/avatar-4.png
