// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVCiSmD2uzxJatREhB-NHiVo8rnv-6Y78',
    appId: '1:651369577703:web:772597c44215c026beb642',
    messagingSenderId: '651369577703',
    projectId: 'lessay-production',
    authDomain: 'lessay-production.firebaseapp.com',
    storageBucket: 'lessay-production.appspot.com',
    measurementId: 'G-JT52JVT3TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlTQBKxZeARM6eRMuDMbAVFHiO5ZRxWGQ',
    appId: '1:651369577703:android:1683396531731a68beb642',
    messagingSenderId: '651369577703',
    projectId: 'lessay-production',
    storageBucket: 'lessay-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3tImW6zxGxdxXVHHOfLsW_pNEIqOsRRk',
    appId: '1:651369577703:ios:51ca4952bceae612beb642',
    messagingSenderId: '651369577703',
    projectId: 'lessay-production',
    storageBucket: 'lessay-production.appspot.com',
    iosClientId: '651369577703-qhu2tl3gmbtqlahar5cnjhro52l9drno.apps.googleusercontent.com',
    iosBundleId: 'com.lessay.learn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3tImW6zxGxdxXVHHOfLsW_pNEIqOsRRk',
    appId: '1:651369577703:ios:3d465b68be4d5b5ebeb642',
    messagingSenderId: '651369577703',
    projectId: 'lessay-production',
    storageBucket: 'lessay-production.appspot.com',
    iosClientId: '651369577703-ntejekr05fge1dg0se1j2f74jebfojdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiLanguageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZcrtCwTYx8ziQEiGYrW1a7G2YdGYS9nI',
    appId: '1:651369577703:web:bfd90f09f7b43454beb642',
    messagingSenderId: '651369577703',
    projectId: 'lessay-production',
    authDomain: 'lessay-production.firebaseapp.com',
    storageBucket: 'lessay-production.appspot.com',
    measurementId: 'G-VBLPNZCQ1G',
  );

}