// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-yca2ygkAhZdkEL7r7tp-B4iX9fq2-eE',
    appId: '1:203834336057:web:d4ae28464089bbbae03ee8',
    messagingSenderId: '203834336057',
    projectId: 'lessay',
    authDomain: 'lessay.firebaseapp.com',
    storageBucket: 'lessay.appspot.com',
    measurementId: 'G-6W3CCQZ4CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoMcVKsItcS7Q1SQ8LbIea3v-qJceoBKY',
    appId: '1:203834336057:android:794ccf9242ef9097e03ee8',
    messagingSenderId: '203834336057',
    projectId: 'lessay',
    storageBucket: 'lessay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApSRvyqqcIwOFeF4u_jb6j0OG_Jya90Os',
    appId: '1:203834336057:ios:1f098c31b145b956e03ee8',
    messagingSenderId: '203834336057',
    projectId: 'lessay',
    storageBucket: 'lessay.appspot.com',
    iosBundleId: 'com.example.aiLanguageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApSRvyqqcIwOFeF4u_jb6j0OG_Jya90Os',
    appId: '1:203834336057:ios:1f098c31b145b956e03ee8',
    messagingSenderId: '203834336057',
    projectId: 'lessay',
    storageBucket: 'lessay.appspot.com',
    iosBundleId: 'com.example.aiLanguageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-yca2ygkAhZdkEL7r7tp-B4iX9fq2-eE',
    appId: '1:203834336057:web:22a94c93f2b34193e03ee8',
    messagingSenderId: '203834336057',
    projectId: 'lessay',
    authDomain: 'lessay.firebaseapp.com',
    storageBucket: 'lessay.appspot.com',
    measurementId: 'G-LDY1NXT73S',
  );
}
